#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# Check if there are any active ssl peers connected to RabbitMQ.
- name: rabbitmq | check-tls | Check RabbitMQ TLS state
  become: yes
  command: rabbitmqctl status
  register: ardana_notify_rabbitmq_reset_required
  changed_when: >
    ((not (rabbitmq_tls_enabled | bool)) and
      (ardana_notify_rabbitmq_reset_required.stdout | search("'amqp/ssl'"))) or
    ((rabbitmq_tls_enabled | bool) and
      (not (ardana_notify_rabbitmq_reset_required.stdout |
            search("'amqp/ssl'"))))

- name: rabbitmq | check-tls | Check RabbitMQ inter-node TLS state
  become: yes
  shell: >
    grep 'proto_dist inet_tls' "{{ rabbitmq_etc_dir }}/rabbitmq-env.conf" ||
    true
  register: ardana_notify_rabbitmq_major_change
  changed_when: >
    rabbitmq_tls_replication | bool and
    ardana_notify_rabbitmq_major_change.stdout == ""
