#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: rabbitmq | install | Install RabbitMQ dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: procps

- name: rabbitmq | install | SUSE - Install RabbitMQ application
  become: yes
  zypper:
    name: "{{ item.package }}"
    state: latest
  register: _rabbitmq_install_zypper_result
  with_items: rabbitmq_restart_packages
  when:
    item.upgrade != "" and
    ansible_os_family == 'Suse'

# The epmd.socket unit is enabled by default but only listens on 127.0.0.1,
# while we need it to listen on the management network too.
- name: rabbitmq | install | Create epmd.socket.d directory
  become: yes
  file:
    path: /etc/systemd/system/epmd.socket.d
    state: directory
    mode: 0755
  when:
    ansible_os_family == 'Suse'

- name: rabbitmq | install | SUSE - Create epmd.socket.d/port.conf
  become: yes
  template:
    src: suse/epmd.socket-port.conf.j2
    dest: /etc/systemd/system/epmd.socket.d/port.conf
    mode: 0644
  register: _epmd_socket_conf_result
  when:
    ansible_os_family == 'Suse'

- name: rabbitmq | install | SUSE - Reload systemd for epmd.socket extension
  become: yes
  command: systemctl daemon-reload
  when:
    _epmd_socket_conf_result.changed and
    ansible_os_family == 'Suse'

- name: rabbitmq | install | SUSE - Store registered facts
  set_fact:
    _rabbitmq_install_pkg_result: "{{ _rabbitmq_install_zypper_result }}"
  when: ansible_os_family == 'Suse'

- name: rabbitmq | install | Restart RabbitMQ application
  become: yes
  service:
    name: "{{ rabbitmq_service_name }}"
    state: restarted
  when: _rabbitmq_install_pkg_result.changed

- name: rabbitmq | install | Wait for the RabbitMQ application to start
  become: yes
  command: |
    timeout {{ rabbitmq_start_timeout }}
    rabbitmqctl wait {{ rabbitmq_env.pid_file }}
  changed_when: false
  when: _rabbitmq_install_pkg_result.changed
